### PR TITLE
Fix connection-related leaks and inconsistencies

### LINKED ISSUE #92: State not cleaned up on socket close
https://github.com/baffo32/OpenBCI_NodeJS/tree/1.4.x-socket-close-resources
- [x] A test should be added to ensure write functions fail and connection state is disconnected, after connection close.
- [x] A test should be added for close before writes are complete, that the data is not written on the next connection
- [x] `.connected = false` is only set when `disconnect()` is called, so invalid state will be entered if the dongle is yanked etc.  This should be set in the close listener, and in the error listener, or in a unified internal function such as a `._disconnected()`.
- [x] investigate use and behavior of the function `_reset()` and see how it relates to this.  It may be redundant.  If not, give it a more descriptive name, and call it if needed in the disconnection handler.
- [x] Some code checks for connection with `this.serial`, and some with `this.connected`.  Because the serial port library does not allow to re-open a serial port to a different path, it is somewhat appropriate that presence of the serial object be roughly equated with connection (path may change if dongle is yanked and reinserted).  Still, this code should be unified to have one canonical way of detecting connection, for maintainability: perhaps replace `this.connected` with a public API function that checks for `this.serial`.  At the moment the `this.serial` code is incorrect because of the next task item.
  - An issue here is that the serial port has more states that simply here or not here.  Notably it can be present and not connected immediately after constructor call.  We can code such that it is never present and 'disconnecting', but this could be hard in the future for others to continue to maintain.
  - So it is reasonable for connection state to be separate from serial presence.  But of note is that when connected, the serial will always be present.  The reverse is not true.  So really, if `isConnected()` checks both, I just need to check the uses of it that they are doing what is intended, given these state relationships.  I haven't come up with a possible situation where that wouldn't be the case.
  - [ ] Crucially, `this.serial` must not be used unless `this.isConnected()` is checked first.  Perhaps this is obvious, though.
- [x] `this.serial` is not removed, nor are its error, data, and close listeners, upon disconnection.  This should be done in parallel with, or in replacement of, `this.connected = false`.
- [x] the write function state should be cleaned up when socket is closed.  the command queue should be emptied, and any other cleanup needed.  If #91 is implemented first, reject write promises when socket is closed.
- [x] A test should be added for behavior choice on close when writes are pending: that they either are, or are not, written out on close.
- [ ] ensure no event listeners are still active when serial object is lost
- [x] ensure no running timeouts, intervals, etc are still active after disconnection

### PR DESCRIPTION
**Pull request by baffo32**
Fixes #92

Notable changes:
- Added a utils test file that tracks `setTimeout()` and `setInterval()` uses that are never `clear`ed.
- Changed `.connected` to `.isConnected()` so that it may be part of the public API
- Paired uses of `.sntpStart` with matching `.sntpStop`
- Raise a few more errors in places where exceptional things happen
- Handled all forms of disconnection and cleaned up state

### CODE REVIEW

**Comment by aj-ptw** [comment]
jaw dropped on the awesomeness that is this pr. just reviewed all the code and it all looks great Karl! Just get those pesky tests passing :) and I'm very happy with this!

**Comment by aj-ptw** [comment]
It's looks like one of your `should` is not passing in the constructor test.

**Comment by baffo32** [comment]
it looks like it's because the SNTP is timing out or failing occasionally for that test on travis.  

The second failure is reporting that SNTP's `setInterval` is still running after the test has ended because `.sntpStop` was not called

should probably be handled more robustly somehow.  SNTP is rather a kludge anyway right now because the two driver objects reference the same sntp object and will alter each other's state

**Comment by aj-ptw** [comment]
Agreed, I think there is a lot of clean up that needs to happen with `sntp`

**Comment by baffo32** [comment]
because of https://github.com/hueniverse/sntp/issues/14 (`sntp.start` does not report errors), I added a call to `sntpGetOffset`, which does report errors, in `sntpStart` to determine if the options are valid, which adds another 2 seconds to construction time.  had to increase timeouts

**Comment by baffo32** [comment]
yowch.  I can't reproduce these timeouts locally.  Guess I'll need to learn how to set up travis so I can debug this without adding lots of commits to an open pull request.

**Comment by aj-ptw** [comment]
I just looked at the error and saw it's a different one then before. It does look like a timeout, failure to establish the sntp sync, issue that could be causing it. It's been working though so I'm more interested in what was changed within the sntp function to make (expose?) the tests fail.

File: openBCIBoard.js [hunk 1]
```diff
@@ -2149,20 +2174,15 @@ function OpenBCIFactory () {
...
-        if (err) {
-          this.sync.sntpActive = false;
-          reject(err);
-        } else {
-          this.sync.sntpActive = true;
-          resolve();
-          this.emit('sntpTimeLock');
-        }
+      this.sntpGetOffset().then(() => {
+        return new Promise(resolve => Sntp.start(resolve));
```
Comment (aj-ptw) [inline openBCIBoard.js]: This is the line not resolving

**Comment by baffo32** [comment]
In order to add coverage, I added a test for `sntpStart` rejection in the constructor.

But it's never hit because of a bug in sntp (https://github.com/hueniverse/sntp/issues/14).

So I added a call to `sntpGetOffset` into `sntpStart` and used it to detect failure.  This is why it takes so long.

**Comment by aj-ptw** [comment]
Gut feeling that `test/.openBCIBoard-test.js.swp` should be added to the `gitignore` seeing as it's a binary.

**Comment by aj-ptw** [comment]
it's looking good so far!!!

**Comment by baffo32** [comment]
same test failure once on my end https://travis-ci.org/baffo32/OpenBCI_NodeJS/builds/169840347

**Comment by aj-ptw** [comment]
Jeeze this is super inconsistent

**Comment by aj-ptw** [comment]
Karl, is there anything i can do to help you?

**Comment by baffo32** [comment]
looks like it's intertwined with some set of runaway impedance promises.  it only fails when they line up with the parallel sntp.  I'll look into it more later

**Comment by aj-ptw** [comment]
hmm i tried to pull out most of the impedances into a separate testing file, could you please link to the suspected line?

**Comment by baffo32** [comment]
https://travis-ci.org/baffo32/OpenBCI_NodeJS/jobs/169840481#L1297 these impedance-related outputs are some delayed output from the impedance testing file, which was run much earlier.  some impedance process was ongoing when some impedance test decided it didn't need anything more and ended early.

I was thinking maybe of upgrading to a more complex promise library, to track down things like this, but I don't think it is necessary

**Comment by baffo32** [comment]
For the ones that fail, the impedance-related output is generated during the test that fails: https://travis-ci.org/baffo32/OpenBCI_NodeJS/jobs/169840488#L1736 so they are probably related

**Comment by baffo32** [comment]
@aj I've gotten the tests passing.  I pulled in bluebird (for tests only) to track unresolved promises, which revealed a lot of them, all of which I plugged.  Any thoughts?

**Comment by aj-ptw** [comment]
> Changed .connected to .isConnected() so that it may be part of the public API

Should we do the same for `streaming`?

**Comment by aj-ptw** [comment]
> which revealed a lot of them, all of which I plugged. Any thoughts?

everything I'm seeing seems to only drastically increase the quality of promise test coverage. Looks good, I don't think it's decrememnting quality of coverage. Not too sure how to verify this though. I'm happy to merge this with 1.4.0 and begin testing it

**Comment by baffo32** [comment]
Failing test is #115 again

**Comment by aj-ptw** [comment]
Thanks @baffo32 !
