### PR TITLE
Fix promise data processing

### LINKED ISSUE #115: Some samples dropped when received in a large clump.
This is resulting in occasional test timeouts, when samples are processed too infrequently to finish in time.

See the extra debugging output at https://travis-ci.org/baffo32/OpenBCI_NodeJS/jobs/171760737#L338 : the system receives many samples (instances of "a0" in the debug bytes), but processes only two of them ("sample 1", "sample 2").

### PR DESCRIPTION
**Pull request by aj-ptw**
Ideally closes #115 by removing promises from all buffer processing functions.

### CODE REVIEW

File: openBCIBoard.js [hunk 1]
```diff
@@ -1898,13 +1897,13 @@ function OpenBCIFactory () {
...
-        sampleObject.rawPacket = rawPacket;
-        this._finalizeNewSample(sampleObject);
-      })
-      .catch(err => console.log('Error in _processPacketStandardAccel', err));
+    try {
+      let sample = openBCISample.parseRawPacketStandard(rawPacket, this.channelSettingsArray, true);
+      sample.rawPacket = rawPacket;
+      this._finalizeNewSample(sample);
+    } catch (err) {
+      throw err;
```
Comment (baffo32) [inline openBCIBoard.js]: note that because there is nothing in the catch(){} block here; this try/catch structure could be removed with no change in behavior

File: openBCISample.js [hunk 2]
```diff
@@ -31,30 +31,39 @@ var sampleModule = {
   *                  calling OpenBCIConstans.channelSettingsArrayInit(). The most important rule here is that it is
   *                  Array of objects that have key-value pair {gain:NUMBER}
   * @param convertAuxToAccel (optional) {Boolean} - Do you want to convert to g's? (Defaults to true)
-  * @returns {Promise} - A sample object
   */
   parseRawPacketStandard: (dataBuf, channelSettingsArray, convertAuxToAccel) => {
     const defaultChannelSettingsArray = k.channelSettingsArrayInit(k.OBCINumberOfChannelsDefault);
+    if (k.isUndefined(convertAuxToAccel) && k.isUndefined(channelSettingsArray)) {
```
Comment (baffo32) [inline openBCISample.js]: The rearrangement of the logic here will only provide a default value for `channelSettingsArray` if `convertAuxToAccel` is also unspecified, leaving `channelSettingsArray` undefined if `convertAuxToAccel` is provided.  I mention it because this was not the behavior of the code previously.  Is this an intended change?

File: openBCISample.js [hunk 3]
```diff
@@ -31,30 +31,39 @@ var sampleModule = {
...
-          resolve(sampleObject);
-        }).catch(err => reject(err));
-      } else {
-        parsePacketStandardRawAux(dataBuf, channelSettingsArray).then(sampleObject => {
-          resolve(sampleObject);
-        }).catch(err => reject(err));
-      }
-    });
+    // Check to make sure data is not null.
+    if (k.isUndefined(dataBuf) || k.isNull(dataBuf) || k.isNumber(dataBuf)) {
```
Comment (baffo32) [inline openBCISample.js]: `k.isNumber` looks like a typo here?

File: openBCISample.js [hunk 4]
```diff
@@ -31,30 +31,39 @@ var sampleModule = {
   *                  calling OpenBCIConstans.channelSettingsArrayInit(). The most important rule here is that it is
   *                  Array of objects that have key-value pair {gain:NUMBER}
   * @param convertAuxToAccel (optional) {Boolean} - Do you want to convert to g's? (Defaults to true)
-  * @returns {Promise} - A sample object
```
Comment (baffo32) [inline openBCISample.js]: On line 603 the syntax `@returns {object}` is used, perhaps that should be filled in here too

**Comment by baffo32** [comment]
This looks great to me.  I think it really increases the clarity (and efficiency) of the code to not use promises for synchronous internal functions.  I found a few minor issues which I made line comments for but are not that important.  I didn't review the tests, and I don't have an understanding of the packet processing code to really know what is going on in context yet.

One thing is missing: I don't see anywhere that these newly thrown errors are caught and emitted.  That's important, so the user of the library can know about them.  That might happen in _processBytes or some common wrapping function with code such as
```
try {
  // do stuff that could cause a throw somewhere inside
} catch(err) {
  this.emit('error', err);
  // do anything needed to clean up after an error, perhaps nothing
}
```
then the user of the library can listen to the error event to know when something goes wrong.

File: openBCIBoard.js [hunk 5]
```diff
@@ -1930,125 +1931,125 @@ function OpenBCIFactory () {
...
+
+      return temp;
+    } catch (err) {
+      console.log(err);
+      // Emit the bad sync object for fun
+      let badObject = openBCISample.newSyncObject();
+      badObject.timeOffsetMaster = this.sync.timeOffsetMaster;
+      this.emit('synced', badObject);
+      // Set back to null
+      this.sync.curSyncObj = null;
```
Comment (aj-ptw) [inline openBCIBoard.js]: good call Karl, I changed this to not throw and error when it is emitting a bad sync object.

File: openBCIBoard.js [hunk 6]
```diff
@@ -1930,125 +1931,125 @@ function OpenBCIFactory () {
...
+      // Fix the curParsingMode back to normal
+      this.curParsingMode = k.OBCIParsingNormal;
+      // Emit the bad sync object for fun
+      var badObject = openBCISample.newSyncObject();
+      badObject.timeOffsetMaster = this.sync.timeOffsetMaster;
+      this.emit('synced', badObject);
+      // Set back to null
+      this.sync.curSyncObj = null;
+      // Return will exit this method with the err
+      throw new Error('Missed the time sync sent confirmation');
```
Comment (aj-ptw) [inline openBCIBoard.js]: This has been eliminated

File: openBCIBoard.js (hunk 1 above)
Comment (aj-ptw) [inline openBCIBoard.js]: should we just print the error instead? At some point we are going to have to internally absorb the errors.

File: openBCISample.js (hunk 4 above)
Comment (aj-ptw) [inline openBCISample.js]: Great thanks, addressed.

File: openBCISample.js (hunk 2 above)
Comment (aj-ptw) [inline openBCISample.js]: Awesome eyes Karl! This was when I was starting with callbacks and then switched, this change has been undone.

File: openBCISample.js (hunk 3 above)
Comment (aj-ptw) [inline openBCISample.js]: They are helper functions defined in the constants file. I just added tests for them too.

File: openBCISample.js [hunk 7]
```diff
@@ -591,46 +600,36 @@ function newSyncObject () {
 * @param channelSettingsArray {Array} - An array of channel settings that is an Array that has shape similar to the one
 *                  calling OpenBCIConstans.channelSettingsArrayInit(). The most important rule here is that it is
 *                  Array of objects that have key-value pair {gain:NUMBER}
-* @returns {Promise} - Fulfilled with a sample object that has form:
+* @returns {object} Sample.
+*                   `error` is an Error
```
Comment (aj-ptw) [inline openBCISample.js]: awesome thanks

File: openBCIBoard.js [hunk 8]
```diff
@@ -1914,141 +1913,149 @@ function OpenBCIFactory () {
...
+      if (this.options.verbose) console.log(err);
+      // Emit the bad sync object
+      let badObject = openBCISample.newSyncObject();
+      badObject.timeOffsetMaster = this.sync.timeOffsetMaster;
+      // Capture the error in the object
+      badObject.error = err;
+      // Emit
+      this.emit('synced', badObject);
+      // Set back to null
+      this.sync.curSyncObj = null;
```
Comment (baffo32) [inline openBCIBoard.js]: forgot to return badObject here

File: changelog.md [hunk 9]
```diff
@@ -30,6 +31,7 @@
 * Fixed bug where resources were not cleaned up if connect was called twice
 * Fixed bug where serial data was written after disconnection
 * Fixed bug where unexpected disconnection was not detected
+* Fixed bug where promises used in packet processing allowed for context/process switch.
```
Comment (baffo32) [inline changelog.md]: I mis-spoke earlier; javascript doesn't actually allow for context switching, and can't prevent process switching, but the change fixes possible mis-ordering of responses since the order in which promises are resolved is not guaranteed

File: changelog.md [hunk 10]
```diff
@@ -18,8 +18,8 @@
 * The setting for simulatorInjectLineNoise has changed from `None` to `none`
 * connect() will now fail if already connected
 * The constructor will throw an error now if an invalid option is passed
-* The undocumented `.connected` field has been removed, replaced by `.isConnected()`
-* The undocumented `.streaming` field has been removed, replaced by `.isStreaming()`
+* The undocumented `.connected` field has been removed, replaced by `.isConnected()`. Removed from docs.
+* The undocumented `.streaming` field has been removed, replaced by `.isStreaming()`. Removed from docs.
```
Comment (baffo32) [inline changelog.md]: oh my goodness I totally never saw that these were actually documented, I would never have changed them
